<a href="https://colab.research.google.com/github/RaymondLeong94/Flatiron_Capstone_Project-/blob/main/Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.youtube.com/watch?v=Fuw0wv3X-0o

In [41]:
import pandas as pd
import json
from google.colab import drive

drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


In [42]:
%cd gdrive/MyDrive

[Errno 107] Transport endpoint is not connected: 'gdrive/MyDrive'
/content/gdrive/MyDrive


In [54]:
import json
preprocessed3 = pd.read_json('/content/gdrive/MyDrive/final_preprocessed_data.json', encoding='utf8') 

In [55]:
practice_set= preprocessed3
practice_set.head()

business_id  stars_x  review_count ByAppointmentOnly  \
0  MTSW4McQd7CbVtyjqoe9mw      4.0            80             False   
1  MTSW4McQd7CbVtyjqoe9mw      4.0            80             False   
2  MTSW4McQd7CbVtyjqoe9mw      4.0            80             False   
3  MTSW4McQd7CbVtyjqoe9mw      4.0            80             False   
4  MTSW4McQd7CbVtyjqoe9mw      4.0            80             False   

  BusinessAcceptsCreditCards CoatCheck RestaurantsTakeOut RestaurantsDelivery  \
0                      False   unknown               True               False   
1                      False   unknown               True               False   
2                      False   unknown               True               False   
3                      False   unknown               True               False   
4                      False   unknown               True               False   

  Caters     WiFi  ... stars_y  \
0   True  u'free'  ...       4   
1   True  u'free'  ...       4   
2   True  u'free'  ...       5   
3   True  u'free'  ...       5   
4   True  u'free'  ...       4   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     text  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 This is nice little Chinese bakery in the heart of Philadelphia's Chinatown! The female cashier was very friendly (flirtatious!) and the pastries shown in nicely adorned display cases. I stopped by early one evening had a sesame ball, which was filled with bean paste. The glutinous rice of the ball was nicely flavored, similar to Bai Tang Gao. Definitely as place worth stopping at if you are in the area.   
1                                                                                                                                                                                                                                                                                                                                                                                       This is the bakery I usually go to in Chinatown.  They have a decent variety of buns and pastries.  Red bean-filled buns, mung bean-filled buns, coconut stuff, egg tarts etc.  If you buy a dozen, they will give you two more for free.  The prices are standard for a Chinese bakery, with most things at approximately $1.  The service has always been good.  They do serve coffee and tea.  There are a couple of tables inside, with usually the expected group of older Chinese guys chillin' in the corner table debating about something.  Great place to

In [56]:
practice_set= practice_set[['nouns_adjec', 'stars_y']]

In [59]:

practice_set = practice_set.reset_index()

In [60]:
practice_set

index  \
0          0   
1          1   
2          2   
3          3   
4          4   
...      ...   
65693  67359   
65694  67360   
65695  67361   
65696  67362   
65697  67363   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  nouns_adjec  \
0                                                                                                                                                                                                                                              'heart', 'philadelphia', 'female', 'cashier', 'pastry', 'show', 'display', 'case', 'evening', 'sesame', 'ball', 'paste', 'rice', 'ball', 'bai', 'tang', 'gao', 'area''nice', 'little', 'bakery', 'chinatown', 'flirtatious', 'adorn', 'fill', 'bean', 'glutinous', 'similar', 'place', 'worth'   
1                                                                                                                                                                       'bakery', 'variety', 'bun', 'pastry', 'bun', 'mung', 'coconut', 'stuff', 'egg', 'tart', 'dozen', 'price', 'standard', 'thing', 'service', 'serve', 'coffee', 'tea', 'couple', 'group', 'guy', 'chillin', 'corner', 'debate', 'something', 'place', 'stock', 'bun', 'town''chinatown', 'decent', 'beanfilled', 'bun', 'free', 'good', 'table', 'old', 'table', 'great'   
2                                                                                                                                                                                                                                                                                                                                                                                  'kind', 'service', 'everyone', 'treat', 'treat', 'judgement', 'theyre', 'favorite''delightful', 'chinatown', 'clean', 'happy', 'delicious', 'ton', 'sweet'   
3                                                                                                                                                                                                                                                                                                                                                                                                                                                 'order', 'graduation', 'event', 'staff', 'nice''niece', 'perfect', 'come', 'future', 'good'   
4      'milk', 'saint', 'honore', 'pastry', 'business', 'boyfriend', 'time', 'cross', 'mind', 'try', 'think', 'year', 'try', 'hkstyle', 'milk', 'tea', 'hook', 'think', 'day', 'week', 'milk', 'tea', 'sugar', 'i', 'zhong', 'gang', 'milk', 'day', 'ice', 'ice', 'etc', 'note', 'try', 'crispy', 'roast', 'pork', 'bun', 'name', 'pork', 'bun', 'crispy', 'roast', 'pork', 'bun''hkstyle', 'sure', 'memorable', 'decide', 'watch', 'good', 'good', 'hkstyle', 'certain', 'lady', 'enough', 'much', 'side', 'wrong', 'roast', 'decent', 'try'   
...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ...   
65693                                                                                                          

In [61]:
#idea from https://www.youtube.com/watch?v=Fuw0wv3X-0o
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [62]:
#convert
practice_set['nouns_adjec']= practice_set['nouns_adjec'].astype(str)

In [63]:
pd.set_option("max_colwidth", None)

In [64]:
practice_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65698 entries, 0 to 65697
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   index        65698 non-null  int64 
 1   nouns_adjec  65698 non-null  object
 2   stars_y      65698 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 1.5+ MB


In [65]:
practice_set['nouns_adjec']

0                                                                                                                                                                                                                                                'heart', 'philadelphia', 'female', 'cashier', 'pastry', 'show', 'display', 'case', 'evening', 'sesame', 'ball', 'paste', 'rice', 'ball', 'bai', 'tang', 'gao', 'area''nice', 'little', 'bakery', 'chinatown', 'flirtatious', 'adorn', 'fill', 'bean', 'glutinous', 'similar', 'place', 'worth'
1                                                                                                                                                                         'bakery', 'variety', 'bun', 'pastry', 'bun', 'mung', 'coconut', 'stuff', 'egg', 'tart', 'dozen', 'price', 'standard', 'thing', 'service', 'serve', 'coffee', 'tea', 'couple', 'group', 'guy', 'chillin', 'corner', 'debate', 'something', 'place', 'stock', 'bun', 'town''chinatown', 'decent', 'beanfilled', 

In [66]:
practice_set['nouns_adjec'] = practice_set['nouns_adjec'].astype(str).apply(lambda x: x.replace('"', ''))

In [67]:
practice_set['nouns_adjec'] = practice_set['nouns_adjec'].apply(lambda x: x.replace('[', ''))
practice_set['nouns_adjec'] = practice_set['nouns_adjec'].apply(lambda x: x.replace(']', ''))
practice_set['nouns_adjec'] = practice_set['nouns_adjec'].apply(lambda x: x.replace(',', ''))

In [68]:
practice_set['nouns_adjec'][0]

"'heart' 'philadelphia' 'female' 'cashier' 'pastry' 'show' 'display' 'case' 'evening' 'sesame' 'ball' 'paste' 'rice' 'ball' 'bai' 'tang' 'gao' 'area''nice' 'little' 'bakery' 'chinatown' 'flirtatious' 'adorn' 'fill' 'bean' 'glutinous' 'similar' 'place' 'worth'"

In [69]:
import nltk
from gensim.models import Word2Vec, KeyedVectors


In [70]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [71]:
practice_set['nouns_adjec'][2]

"'kind' 'service' 'everyone' 'treat' 'treat' 'judgement' 'theyre' 'favorite''delightful' 'chinatown' 'clean' 'happy' 'delicious' 'ton' 'sweet'"

In [72]:
from nltk import word_tokenize
nltk.download('punkt') 

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [73]:
practice_set['nouns_adjec']= practice_set['nouns_adjec'].astype(str)

In [74]:
corpus =  practice_set['nouns_adjec'].map(word_tokenize)


In [75]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [76]:
corpus

0                                                                                                                                                                                         ['heart, ', 'philadelphia, ', 'female, ', 'cashier, ', 'pastry, ', 'show, ', 'display, ', 'case, ', 'evening, ', 'sesame, ', 'ball, ', 'paste, ', 'rice, ', 'ball, ', 'bai, ', 'tang, ', 'gao, ', 'area, '', nice, ', 'little, ', 'bakery, ', 'chinatown, ', 'flirtatious, ', 'adorn, ', 'fill, ', 'bean, ', 'glutinous, ', 'similar, ', 'place, ', 'worth, ']
1                                                                                                ['bakery, ', 'variety, ', 'bun, ', 'pastry, ', 'bun, ', 'mung, ', 'coconut, ', 'stuff, ', 'egg, ', 'tart, ', 'dozen, ', 'price, ', 'standard, ', 'thing, ', 'service, ', 'serve, ', 'coffee, ', 'tea, ', 'couple, ', 'group, ', 'guy, ', 'chillin, ', 'corner, ', 'debate, ', 'something, ', 'place, ', 'stock, ', 'bun, ', 'town, '', chinatown, ', 'decent, ', 'beanfilled, 

In [77]:
vectorizedcorpus.type()

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-77-745c667f9e20>", line 1, in <module>
    vectorizedcorpus.type()
NameError: name 'vectorizedcorpus' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2040, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/

NameError: ignored

In [79]:
#min count = 1 for freq 
#vectorsize = 100 
#windows = amount it will go left and right 
model = Word2Vec(corpus, size=300, min_count = 1, window = 10)

In [80]:
vocabulary = model.wv.vocab

In [81]:
vocabulary


{"'heart": <gensim.models.keyedvectors.Vocab at 0x7f96071de4f0>,
 "'": <gensim.models.keyedvectors.Vocab at 0x7f96071de070>,
 "'philadelphia": <gensim.models.keyedvectors.Vocab at 0x7f96071de970>,
 "'female": <gensim.models.keyedvectors.Vocab at 0x7f96071ded90>,
 "'cashier": <gensim.models.keyedvectors.Vocab at 0x7f96071de100>,
 "'pastry": <gensim.models.keyedvectors.Vocab at 0x7f96071de9d0>,
 "'show": <gensim.models.keyedvectors.Vocab at 0x7f96071defa0>,
 "'display": <gensim.models.keyedvectors.Vocab at 0x7f96071deee0>,
 "'case": <gensim.models.keyedvectors.Vocab at 0x7f96071de1c0>,
 "'evening": <gensim.models.keyedvectors.Vocab at 0x7f96071dea30>,
 "'sesame": <gensim.models.keyedvectors.Vocab at 0x7f96071de4c0>,
 "'ball": <gensim.models.keyedvectors.Vocab at 0x7f96071de8e0>,
 "'paste": <gensim.models.keyedvectors.Vocab at 0x7f96071de7f0>,
 "'rice": <gensim.models.keyedvectors.Vocab at 0x7f96071de940>,
 "'bai": <gensim.models.keyedvectors.Vocab at 0x7f96071debb0>,
 "'tang": <gensim.mo

In [82]:
model1 = model.wv

In [83]:
model1.most_similar('service')

[('menu', 0.8527047634124756),
 ('underwhelmed', 0.8397247791290283),
 ('tough', 0.8395524024963379),
 ('checked', 0.8334258794784546),
 ('impossible', 0.8321889042854309),
 ('affordable', 0.8275795578956604),
 ('fan', 0.826906681060791),
 ('own', 0.824568510055542),
 ('wide', 0.8203316926956177),
 ('real', 0.8202391266822815)]

In [84]:
model1.most_similar("flavor")

[("'optionsalad", 0.7891819477081299),
 ('coffee', 0.7834130525588989),
 ('find', 0.7767985463142395),
 ('chill', 0.7751347422599792),
 ('dissapointed', 0.7652608156204224),
 ('staple', 0.7631983160972595),
 ('picked', 0.7580418586730957),
 ('gyro', 0.7578526139259338),
 ('sneak', 0.757631778717041),
 ('downtown', 0.7559709548950195)]

In [89]:
for_keras= practice_set['nouns_adjec'].values

In [90]:
for_keras

array(["'heart' 'philadelphia' 'female' 'cashier' 'pastry' 'show' 'display' 'case' 'evening' 'sesame' 'ball' 'paste' 'rice' 'ball' 'bai' 'tang' 'gao' 'area''nice' 'little' 'bakery' 'chinatown' 'flirtatious' 'adorn' 'fill' 'bean' 'glutinous' 'similar' 'place' 'worth'",
       "'bakery' 'variety' 'bun' 'pastry' 'bun' 'mung' 'coconut' 'stuff' 'egg' 'tart' 'dozen' 'price' 'standard' 'thing' 'service' 'serve' 'coffee' 'tea' 'couple' 'group' 'guy' 'chillin' 'corner' 'debate' 'something' 'place' 'stock' 'bun' 'town''chinatown' 'decent' 'beanfilled' 'bun' 'free' 'good' 'table' 'old' 'table' 'great'",
       "'kind' 'service' 'everyone' 'treat' 'treat' 'judgement' 'theyre' 'favorite''delightful' 'chinatown' 'clean' 'happy' 'delicious' 'ton' 'sweet'",
       ...,
       "'hand' 'ice' 'coffee' 'terrific' 'guy' 'counter' 'try' 'apartment' 'bella' 'vista' 'place' 'vote' 'apartment' 'good''freak' 'close'",
       "'place' 'chill' 'corner' 'coffee' 'shop' 'baristaowner' 'neighborhood' 'order' 'tea' '

In [91]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [92]:
vocab_size = 300
encoded_reviews = [one_hot(x, vocab_size) for x in for_keras]
print(encoded_reviews)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [93]:
max_length = 10
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[254 228 223 ...  43  35  53]
 [ 31  86  91 ... 249 294 282]
 [ 67 266 247 ... 209 289 279]
 ...
 [237  33 172 ... 172 185 144]
 [ 86 256  86 ...  55  44 166]
 [ 63 193  35 ...  65 282 209]]


In [94]:
embeded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name = "embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [97]:
practice_set.columns

Index(['index', 'nouns_adjec', 'stars_y'], dtype='object')

In [98]:
def stars_transform(x):
  if x >= 4:
    return 1
  else:
    return 0 


practice_set['stars_y'] = practice_set['stars_y'].apply(stars_transform)

In [99]:
practice_set['stars_y'].value_counts()

1    45608
0    20090
Name: stars_y, dtype: int64

In [100]:
sentiment = practice_set['stars_y'].values.flatten()

In [101]:
X = padded_reviews
y=sentiment

In [102]:
sentiment


array([1, 1, 1, ..., 1, 1, 1])

In [103]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 5)             1500      
                                                                 
 flatten (Flatten)           (None, 50)                0         
                                                                 
 dense (Dense)               (None, 1)                 51        
                                                                 
Total params: 1,551
Trainable params: 1,551
Non-trainable params: 0
_________________________________________________________________


In [104]:
model.fit(X, y, epochs=50, verbose=0)

In [105]:
loss, accuracy = model.evaluate(X,y)
accuracy

2054/2054 [==============================] - 5s 2ms/step - loss: 0.4916 - accuracy: 0.7616


0.7616061568260193

In [ ]:
model.get_layer('embedding').get_weights()[0]

array([[-0.08514103, -0.23153287,  0.24459454, -0.3646788 , -0.25075015],
       [-0.2938213 ,  0.07905864,  0.3493986 , -1.0039985 , -0.11557846],
       [-0.34502858, -0.07566555, -0.0161044 , -0.06921784, -0.3675889 ],
       ...,
       [-0.39592603, -0.27611938,  0.35098198,  0.09522876,  0.12187388],
       [-0.31211022, -0.16910024,  0.5180508 , -0.35287592, -0.57010895],
       [-0.465337  , -0.43238527,  0.5847294 , -0.07537656, -0.48818544]],
      dtype=float32)